name: Docker

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  docker:
    uses: czerwonk/go-ci/.github/workflows/docker-publish.yml@v2
    with:
      dockerhub-image: czerwonk/ping_exporter
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
