name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "dist/charts/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  helm:
    uses: czerwonk/go-ci/.github/workflows/helm-release.yml@v2
    with:
      chart-path: dist/charts/ping-exporter
      pages-url: https://czerwonk.github.io/ping_exporter
