name: Test

on:
  push:
  pull_request:

jobs:
  test:
    uses: czerwonk/go-ci/.github/workflows/test.yml@v1
    with:
      build-command: 'CGO_ENABLED=0 go build -v -ldflags="-s -w" -trimpath -o ping_exporter'
